name: Run Unit Tests (docker)

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run LabVIEW Unit Tests in Docker
        uses: KSharma-NI/open-source/run-unit-tests-docker@users/krishsha/run-unit-tests-docker
        with:
          docker_image: nationalinstruments/labview:2026q1-windows
          lv_version: '2026'
          lv_bitness: '64'
          project_path: 'Core\Actor Framework Core.lvproj'
          open_project_before_run: true
          log_level: 'DEBUG'